sudo: required
language: generic

services:
 - docker

before_install:
   - docker build -t poojakho/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true poojakho/docker-react npm run test