language: generic
sudo: required
services:
 - docker

 before_install:
   - docker build -t PoojaKho/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true PoojaKho/docker-react npm run test